# Project: ChienHamNganHa
# Makefile created by Dev-C++ 5.6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"F:/Program/Dev-Cpp/MinGW32/lib" -L"F:/Program/Dev-Cpp/MinGW32/mingw32/lib" -static-libstdc++ -static-libgcc -lbgi -lgdi32 -lcomdlg32 -luuid -loleaut32 -lole32 -lwinmm
INCS     = -I"F:/Program/Dev-Cpp/MinGW32/include" -I"F:/Program/Dev-Cpp/MinGW32/mingw32/include" -I"F:/Program/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include"
CXXINCS  = -I"F:/Program/Dev-Cpp/MinGW32/include" -I"F:/Program/Dev-Cpp/MinGW32/mingw32/include" -I"F:/Program/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include" -I"F:/Program/Dev-Cpp/MinGW32/lib/gcc/mingw32/4.8.1/include/c++"
BIN      = ChienHamNganHa.exe
CXXFLAGS = $(CXXINCS) -lwinmm
CFLAGS   = $(INCS) -lwinmm
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
